### ISSUE TITLE
The code here is correct, the tutorial has the issue

### ISSUE THREAD

**Issue by piannaf** [coderjourney/chords#11]
I'm following along with your tutorials and they are super helpful. So, first off, thank you for writing them.

When copying the code for Footer.js in the tutorial [How to Create Custom React Components](https://coderjourney.com/tutorials/how-to-create-custom-react-components/), I got an error for the line `this.state.year = new Date().getFullYear();`

I went to [the source](https://github.com/coderjourney/chords/blob/e6ae4f6f8c67dc2ebaedfe9f25942a16a4ad1e6c/src/components/Footer.js#L6) to find `this.state = { year: new Date().getFullYear() };`

The source is correct, please update the code in the tutorial.

**Comment by piannaf** [comment]
Also, for [How to Test React Components](https://coderjourney.com/tutorials/how-to-test-react-components/), there are non breaking spaces in the code `&nbsp` that show up as the space character ` ` in the tutorial.

It was confusing when the test failed and initial inspection showed that I didn't type anything wrong. Only after digging deeper into the expected output, did I notice the problem and then confirmed in [the source](https://github.com/coderjourney/chords/blob/master/src/components/ChordEditor.test.js#L25).

**Comment by keiththomps** [comment]
Thanks for pointing these out. I've corrected the code from the first comment. I'm having a hard time getting my static site generator to actually show the text for `&nbsp;` instead of putting a space there (the actually code is correct).
